SET NOCOUNT ON

USE Charity
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='AddressType')
	DROP TABLE [AddressType]
GO

CREATE TABLE [AddressType]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Description] VARCHAR(100) NOT NULL
)
GO

INSERT INTO [AddressType] VALUES ('Billing');
INSERT INTO [AddressType] VALUES ('Shipping');
GO

SELECT * FROM [AddressType] 