SET NOCOUNT ON

USE Charity
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='Address')
	DROP TABLE [Address]
GO

CREATE TABLE [Address]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[AddressTypeId] INT NOT NULL,
	[UserId] INT NOT NULL,
	[Address1] VARCHAR(100),
	[Address2] VARCHAR(100),
	[City] VARCHAR(50),
	[State] VARCHAR(100),
	[Zipcode] VARCHAR(20)
)