SET NOCOUNT ON

USE Charity
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='ContactType')
	DROP TABLE [ContactType]
GO

CREATE TABLE [ContactType]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Description] VARCHAR(100) NOT NULL
)
GO

INSERT INTO [ContactType] VALUES ('Home');
INSERT INTO [ContactType] VALUES ('Mobile');
INSERT INTO [ContactType] VALUES ('Work');
GO

SELECT * FROM [ContactType]