SET NOCOUNT ON

USE Charity
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='Contact')
	DROP TABLE [Contact]
GO

CREATE TABLE [Contact]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[ContactTypeId] INT NOT NULL,
	[UserId] INT NOT NULL,
	[Number] VARCHAR(100)
)