SET NOCOUNT ON

USE Charity
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='CreditCard')
	DROP TABLE [CreditCard]
GO

CREATE TABLE [CreditCard]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[CreditCardTypeId] INT NOT NULL,
	[UserId] INT NOT NULL,
	[Number] VARCHAR(100),
	[CVV] VARCHAR(5)
)