SET NOCOUNT ON

USE Charity
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='Items')
	DROP TABLE [Items]
GO

CREATE TABLE [Items]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[OrganizationId] INT NOT NULL,
	[UserId] INT NOT NULL,
	[IsAnonymous] BIT NULL,
	[Title] VARCHAR(100) NOT NULL,
	[Description] VARCHAR(255) NOT NULL,
	[CreateDate] DATETIME NOT NULL,
	[StartDate] DATETIME NOT NULL,
	[EndDate] DATETIME NOT NULL,
	[CashValue] MONEY NOT NULL,
	[InitialBid] MONEY NOT NULL,
	[BidIncrement] MONEY NOT NULL,
	[Status] INT NOT NULL,
	[PurchasedBy] INT NOT NULL
)
GO