SET NOCOUNT ON

USE Charity
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='ItemsImages')
	DROP TABLE [ItemsImages]
GO

CREATE TABLE [ItemsImages]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[ItemId] INT NOT NULL,
	[UserId] INT NOT NULL,
	[SequenceNo] INT NOT NULL,
	[Description] VARCHAR(100) NULL,
	[Image] IMAGE NULL
)
GO
