SET NOCOUNT ON

USE Charity
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='NotificationType')
	DROP TABLE [NotificationType]
GO

CREATE TABLE [NotificationType]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Description] VARCHAR(100) NOT NULL
)
GO

INSERT INTO [NotificationType] VALUES ('New User');
INSERT INTO [NotificationType] VALUES ('PasswordReset');
GO

SELECT * FROM [NotificationType] 