SET NOCOUNT ON

USE Charity
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='Notifications')
	DROP TABLE [Notifications]
GO

CREATE TABLE [Notifications]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[UserId] INT NOT NULL,
	[NotificationType] INT NOT NULL,
	[Timestamp] DATETIME NOT NULL
)
GO