SET NOCOUNT ON

USE Charity
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='Users')
	DROP TABLE [Users]
GO

CREATE TABLE [Users]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[OrganizationId] INT NOT NULL,
	[UserSecurity] INT NOT NULL,
	[Email] VARCHAR(100) NOT NULL,
	[Password] VARCHAR(100) NULL,
	[FirstName] VARCHAR(100) NOT NULL,
	[LastName] VARCHAR(100) NOT NULL,
	[Status] INT NOT NULL,
	[AcceptedTerms] BIT NULL
)
GO